name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build android app
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew  :common:jvmTest  --no-daemon
      - name: Build iOS shared code
        run: ./gradlew :common:compileKotlinIosArm64


  androidTest:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          script: ./gradlew connectedAndroidTest